FROM node:14-alpine

# Crear directorio de trabajo de la aplicación
WORKDIR /usr/src/app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar archivos de la aplicación
COPY . .

# Compilar la aplicación
RUN npm run build

# Puerto expuesto por la aplicación Nuxt.js
EXPOSE 3000

# Comando para iniciar el servidor
CMD npm run start
