FROM php:7.4-fpm

# Instalar dependencias
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo_mysql mbstring zip exif pcntl bcmath xml

# Copiar archivos de la aplicación
WORKDIR /var/www/html
COPY . .

# Instalar dependencias de composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

# Copiar archivo de configuración de Laravel
COPY .env.example .env

# Generar la clave de la aplicación
RUN php artisan key:generate

# Puerto expuesto por la aplicación Laravel
EXPOSE 8000

# Comando para iniciar el servidor
CMD php artisan serve --host=0.0.0.0 --port=8000
